name: Typescript Checks

on:
  workflow_call:

jobs:
  check_typescript:
    name: Check Typescript library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/typescript

      - name: Build
        run: npm run build
        working-directory: ./src/typescript

      - name: Test
        run: npm test
        working-directory: ./src/typescript

      - name: Lint
        run: npm run lint
        working-directory: ./src/typescript

  check_typescript_chatbot:
    name: Check Typescript chatbot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build and link mcp-server-in-aws-lambda package
        run: npm ci && npm run build && npm link
        working-directory: ./src/typescript

      - name: Install dependencies
        run: npm ci && npm link mcp-server-in-aws-lambda
        working-directory: ./examples/chatbots/typescript

      - name: Build
        run: npm run build
        working-directory: ./examples/chatbots/typescript
